services:
  # Backend API Service
  - type: web
    name: curtain-lights-api
    runtime: python3
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: GOVEE_API_KEY
        sync: false
      - key: GOVEE_DEVICE_ID
        sync: false
      - key: GOVEE_MODEL
        value: H70B1
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: APP_BASE_URL
        value: https://curtain-lights-api.onrender.com
      - key: FRONTEND_URL
        value: https://curtain-lights-frontend.onrender.com
      - key: GOOGLE_CLIENT_EMAIL
        sync: false
      - key: GOOGLE_PRIVATE_KEY
        sync: false
      - key: YT_API_KEY
        sync: false

  # Frontend Static Site
  - type: web
    name: curtain-lights-frontend
    runtime: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://curtain-lights-api.onrender.com 